services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - nextcloud_backend
    container_name: contenedor-cobros-backend
networks:
  nextcloud_backend:
    external: true
